### ISSUE TITLE
Failed docker-compose with 'flywayInitializer'

### ISSUE THREAD

**Issue by JesoosSoz** [Mobility-Data-Space/Deployment-Examples#2]
After executing Docker-compose up with the latest changes of the repository, the build is failing with the following error message:
![image](https://user-images.githubusercontent.com/39771284/196204668-4664f4b4-ae54-4fe6-9b2b-a0a89bea8f5e.png)
Setting SPRING_FLYWAY_ENABLED=false fixes the problem, but I don't think this should be the workaround?

### Environment
* Version 1.2.0 of the GitHub Repository
* Docker version 20.10.18
* Ubuntu 20.04.5 LTS

### Steps to reproduce
1. Changing the keystore.p12
2. Changing in the config.json "ids:maintainer", "ids:curator", "ids:title@value", "ids:accessURL@id" and "ids:connectorDescription@id"
3. Executing docker-compose up

**Comment by SebastianOpriel** [comment]
Thanks for your feedback. The issue is, that you most probably have used docker-compose in the last version without flyway enabled and created the database. Two solutions exist: 
Either delete the database and build it from scatch via `docker-compose down -v` or set flyway migration baseline:
```
      - SPRING_FLYWAY_BASELINEVERSION=8.0.1
      - SPRING_FLYWAY_BASELINEONMIGRATE=true
```
You may need to adjust the version to the version, you started the DSC before.
